import React from 'react';
import MarketChart from './MarketChart';
const signed=n=>`${Number(n)>0?'+':''}${Number(n).toFixed(1)}%`;
// The indexes slide intentionally carries no source paragraph or footer label:
// both were removed as redundant. The other context slides keep theirs.
export function MarketIndexesSlide({data, kicker = 'MARKET CONTEXT', title = 'Year-to-date market snapshot'}) {
 const ready=data?.indexes?.length>=4&&data.indexes.every(i=>i.return !== '' && i.return != null && Number.isFinite(Number(i.return)));
 if(!ready) return <div className="indexes-slide"><div className="report-heading"><div><span className="slide-kicker">{kicker}</span><h2>{title}</h2></div><span>Awaiting sourced data</span></div><div className="data-pending"><span className="slide-kicker">NO MARKET SNAPSHOT LOADED</span><h3>This automatic slide is ready for the sourced index file.</h3><p>Upload report data in the component step to populate S&P 500, Nasdaq, emerging-markets and MSCI year-to-date returns. No market values are invented from the holdings file.</p></div></div>;
 const ranked=[...data.indexes].sort((a,b)=>Number(b.return)-Number(a.return));
 return <div className="indexes-slide"><div className="report-heading"><div><span className="slide-kicker">{kicker}</span><h2>{title}</h2></div><span>Through {data.asOf}</span></div><div className="index-chart-layout"><MarketChart indexes={data.indexes}/><div className="index-grid">{ranked.map((index,i)=><div className="index-card" key={index.id}><div><span>{index.label}</span><b>{signed(index.return)}</b></div><p>{index.region}</p><div className="index-bar"><i style={{width:`${Math.min(100,Math.abs(Number(index.return))*3)}%`,marginLeft:Number(index.return)<0?`${Math.max(0,100-Math.abs(Number(index.return))*3)}%`:0,background:Number(index.return)>=0?(i===0?'#1b2a4a':'#4e7fae'):'#9bb6cf'}}/></div></div>)}</div></div></div>;
}
export function MarketIndexesEditor({data,onChange,onRefresh,loading,error}) {
 return <section className="market-editor index-editor"><div className="editor-heading"><div><h3>Automatic market snapshot</h3><p>YTD data loads from Yahoo Finance when the workspace opens.</p></div><button className="secondary" type="button" disabled={loading} onClick={onRefresh}>{loading?'Refreshing…':'Refresh YTD data'}</button></div><div className="editor-status">{data.asOf?<span className="live-status">Current through {data.asOf}</span>:<span className="helper">No automatic snapshot loaded yet.</span>}{error&&<span className="errors" role="alert">{error}</span>}</div><div className="editor-meta"><label className="field-label">Through date<input type="date" value={data.asOf} onChange={e=>onChange({...data,asOf:e.target.value})}/></label><label className="field-label">Return basis<input value={data.basis} placeholder="YTD total return" onChange={e=>onChange({...data,basis:e.target.value})}/></label></div><div className="index-inputs">{data.indexes.map((index,i)=><div className="index-input-row" key={index.id}><label className="field-label">{index.label}<input type="number" step="0.01" value={index.return} onChange={e=>onChange({...data,indexes:data.indexes.map((v,j)=>i===j?{...v,return:e.target.value}:v)})}/></label><label className="field-label">Region label<input value={index.region} onChange={e=>onChange({...data,indexes:data.indexes.map((v,j)=>i===j?{...v,region:e.target.value}:v)})}/></label></div>)}</div><label className="field-label">Source<input maxLength={240} value={data.source} onChange={e=>onChange({...data,source:e.target.value})}/></label><p className="helper">The same region labels are used to calculate the client holdings attribution slide when the upload includes a matching region column.</p></section>;
}
export function SectorPerformanceEditor({data,onChange}) {
 return <section className="market-editor"><div className="editor-heading"><div><h3>Sector YTD performance</h3><p>Upload sourced market data or enter current figures</p></div></div>
 <div className="editor-meta"><label className="field-label">Through date<input type="date" value={data.asOf} onChange={e=>onChange({...data,asOf:e.target.value})}/></label><label className="field-label">Return basis<select value={data.basis} onChange={e=>onChange({...data,basis:e.target.value})}><option value="">Choose basis</option><option>Price return</option><option>Total return</option><option>As reported (return basis unspecified)</option></select></label></div>
 <div className="sector-inputs">{data.sectors.map((s,i)=><label className="field-label" key={s.name}>{s.name}<div className="percent-field"><input aria-label={`${s.name} YTD return`} type="number" step="0.01" min="-100" value={s.return} onChange={e=>onChange({...data,sectors:data.sectors.map((v,j)=>i===j?{...v,return:e.target.value}:v)})}/><span>%</span></div></label>)}</div>
 <label className="field-label">Source<input maxLength={240} value={data.source} onChange={e=>onChange({...data,source:e.target.value})}/></label><p className="helper">Enter a sourced return for every sector. These returns are separate from the daily holdings-weight feed.</p></section>;
}
export function EarningsEditor({data,onChange}) {
 const group=(key,label)=><div className="earnings-fields"><h4>{label}</h4>{data[key].map((s,i)=><div className="earnings-field-row" key={i}><label className="field-label">Period<input maxLength={16} value={s.period} onChange={e=>onChange({...data,[key]:data[key].map((v,j)=>i===j?{...v,period:e.target.value}:v)})}/></label><label className="field-label">YoY growth (%)<input aria-label={`${s.period} earnings growth`} type="number" step="0.1" value={s.growth} onChange={e=>onChange({...data,[key]:data[key].map((v,j)=>i===j?{...v,growth:e.target.value}:v)})}/></label><label className="field-label">Status<select value={s.kind} onChange={e=>onChange({...data,[key]:data[key].map((v,j)=>i===j?{...v,kind:e.target.value}:v)})}><option>Reported</option><option>Estimate</option></select></label></div>)}</div>;
 return <section className="market-editor"><div className="editor-heading"><div><h3>S&P 500 earnings expectations</h3><p>Upload sourced market data or enter current estimates</p></div></div>
 <label className="field-label">As of<input type="date" value={data.asOf} onChange={e=>onChange({...data,asOf:e.target.value})}/></label>
 {group('quarters','Quarterly momentum')}{group('years','Annual outlook')}
 <label className="field-label">Source<input maxLength={300} value={data.source} onChange={e=>onChange({...data,source:e.target.value})}/></label><p className="helper">Reported and estimated growth remain distinct. The chart uses growth rates, not inferred EPS amounts.</p></section>;
}
export function SectorPerformanceSlide({data}) {
 const ranked=[...data.sectors].sort((a,b)=>Number(b.return)-Number(a.return));
 const high=Number(ranked[0].return), low=Number(ranked.at(-1).return),pos=Math.max(0,high),neg=Math.max(0,-low),span=pos+neg||1,zero=260+neg/span*470;
 return <div className="context-slide"><div className="report-heading"><div><span className="slide-kicker">MARKET CONTEXT</span><h2>Sector leadership, year to date</h2></div><span>Through {data.asOf}</span></div>
 <div className="sector-performance-layout"><svg viewBox="0 0 830 388" role="img" aria-label="S&P 500 sector YTD returns ranked highest to lowest"><line x1={zero} x2={zero} y1="10" y2="381" stroke="#c5d3e2"/>{ranked.map((s,i)=>{const value=Number(s.return),w=Math.abs(value)/span*470,y=i*33+14;return <g key={s.name}><text x="0" y={y+17} fill="#1b2a4a" fontSize="17">{s.name}</text><rect x={value<0?zero-w:zero} y={y} width={w} height="23" rx="2" fill={i===0?'#1b2a4a':value<0?'#91b2d6':'#487aad'}/><text x={value<0?zero-w-8:zero+w+8} y={y+17} textAnchor={value<0?'end':'start'} fill="#1b2a4a" fontSize="17">{signed(value)}</text></g>;})}</svg>
 <aside className="market-takeaway"><span className="slide-kicker">LEADERSHIP GAP</span><strong>{(high-low).toFixed(1)}<small>pp</small></strong><p>between {ranked[0].name} and {ranked.at(-1).name}.</p><div/><b>{ranked[0].name}</b><p>Highest YTD return<br/>{signed(high)}</p><b>{ranked.at(-1).name}</b><p>Lowest YTD return<br/>{signed(low)}</p></aside></div>
 <p className="context-source">{data.source} Through {data.asOf}. {data.basis}. Unmanaged indices; past performance does not guarantee future results.</p></div>;
}
export function EarningsSlide({data}) {
 const values=data.years.map(s=>Number(s.growth)),pos=Math.max(0,...values),neg=Math.max(0,...values.map(v=>-v)),scale=180/(pos+neg||1),zero=35+pos*scale;
 return <div className="context-slide"><div className="report-heading"><div><span className="slide-kicker">MARKET CONTEXT</span><h2>S&P 500 earnings outlook</h2></div><span>As of {data.asOf}</span></div>
 <div className="earnings-layout"><div className="quarterly-momentum"><h3>Quarterly momentum</h3>{data.quarters.map((s,i)=><div className="earnings-metric" key={i}><div><b>{s.period}</b><span>{s.kind}</span></div><strong>{signed(s.growth)}</strong><p>Year-over-year earnings growth</p></div>)}</div><div className="annual-outlook"><h3>Annual outlook</h3><svg viewBox="0 0 430 300" role="img" aria-label="Annual S&P 500 earnings growth outlook"><line x1="20" x2="410" y1={zero} y2={zero} stroke="#bbcade"/>{data.years.map((s,i)=>{const v=Number(s.growth),h=Math.abs(v)*scale,x=75+i*190;return <g key={i}><rect x={x} y={v>=0?zero-h:zero} width="90" height={h} rx="3" fill={s.kind==='Estimate'?'#8cb0dc':'#1b2a4a'}/><text x={x+45} y={v>=0?zero-h-12:zero+h+25} textAnchor="middle" fill="#1b2a4a" fontSize="26" fontWeight="600">{signed(v)}</text><text x={x+45} y="262" textAnchor="middle" fill="#1b2a4a" fontSize="19">{s.period}</text><text x={x+45} y="286" textAnchor="middle" fill="#456a94" fontSize="14">{s.kind}</text></g>;})}</svg><p>Annual earnings growth · year over year</p></div></div>
 <p className="context-source">{data.source} As of {data.asOf}. Estimates may change; quarterly and annual periods are shown separately.</p></div>;
}
