import React from 'react';
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const colors=['#1b2a4a','#315d8c','#5d87b0','#8aa9c8','#afc5dc','#d5e0eb'];
export function PortfolioOverview({holdings,equity}) {
 const ranked=[...holdings].sort((a,b)=>b.value-a.value),total=ranked.reduce((n,h)=>n+h.value,0),topCount=Math.min(3,ranked.length),top=ranked.slice(0,topCount).reduce((n,h)=>n+h.value,0)/total*100;
 const largest=ranked[0];
 const active=equity&&[...equity.sectors].sort((a,b)=>Math.abs(b.portfolio-b.benchmark)-Math.abs(a.portfolio-a.benchmark))[0];
 return <div className="overview-slide"><span className="slide-kicker">PORTFOLIO POSITIONING</span><h2>What stands out in this portfolio</h2>
 <div className="overview-stats"><div><span>Portfolio value</span><b>{money(total)}</b></div><div><span>Positions</span><b>{holdings.length}</b></div><div><span>Largest position</span><b>{largest.ticker}<small>{(largest.value/total*100).toFixed(1)}%</small></b></div></div>
 <div className="executive-panels"><div className="executive-primary"><span>CONCENTRATION</span><strong>{top.toFixed(1)}<small>%</small></strong><h3>in the {topCount} largest positions</h3><p>{ranked.slice(0,topCount).map(h=>h.ticker).join(', ')} account for {money(total*top/100)} of the portfolio.</p></div><div className="executive-secondary"><span>{active?'SECTOR POSITIONING':'PORTFOLIO BALANCE'}</span><h3>{active?`${active.name}: ${active.portfolio>=active.benchmark?'+':''}${(active.portfolio-active.benchmark).toFixed(1)} pp`:`${(100-top).toFixed(1)}% outside the top ${topCount}`}</h3><p>{active?`The largest absolute sector difference versus ${equity.benchmark_short||equity.benchmark_label}. Your weight is ${active.portfolio.toFixed(1)}%, compared with ${active.benchmark.toFixed(1)}%.`:`The remaining ${Math.max(0,holdings.length-topCount)} positions represent ${money(total*(100-top)/100)}. Position count alone does not measure diversification.`}</p><div className="summary-divider"/><span>REVIEW FOCUS</span><p>{active?'Review the sector tilt alongside your intended allocation and the contribution of the largest positions.':'Review the largest positions before considering whether additional holdings change the overall exposure.'}</p></div></div>
 </div>;
}
export function PortfolioAllocation({holdings,equity}) {
 const ranked=[...holdings].sort((a,b)=>b.value-a.value),total=ranked.reduce((n,h)=>n+h.value,0);
 const slices=ranked.length>6?[...ranked.slice(0,5),{ticker:'Other',value:ranked.slice(5).reduce((n,h)=>n+h.value,0)}]:ranked;
 let cursor=0;const stops=slices.map((h,i)=>{const start=cursor;cursor+=h.value/total*100;return `${colors[i]} ${start}% ${cursor}%`;}).join(',');
 const sectors=equity&&[...equity.sectors].filter(s=>s.portfolio>0).sort((a,b)=>b.portfolio-a.portfolio);
 return <div className="composition-slide"><span className="slide-kicker">PORTFOLIO COMPOSITION</span><h2>Where your exposure sits</h2><div className="composition-layout"><div className="position-mix"><h3>Position weights</h3><div className="allocation-donut" style={{background:`conic-gradient(${stops})`}} role="img" aria-label="Portfolio position allocation. Exact weights are listed in the legend."><div className="allocation-donut-center"><strong>{holdings.length}</strong><span>positions</span></div></div><div className="composition-legend">{slices.map((h,i)=><div key={h.ticker}><i style={{background:colors[i]}}/><b>{h.ticker}</b><span>{(h.value/total*100).toFixed(1)}%</span></div>)}</div></div><div className="exposure-mix"><h3>{sectors?'Sector composition':'Position concentration'}</h3>{(sectors||ranked.slice(0,5).map(h=>({name:h.ticker,portfolio:h.value/total*100}))).slice(0,6).map(s=><div className="composition-row" key={s.name}><div><span>{s.name}</span><b>{s.portfolio.toFixed(1)}%</b></div><div><i style={{width:`${s.portfolio}%`}}/></div></div>)}<p className="composition-note">{sectors?`${sectors.length} sectors represented. Classifications follow the sector data used in this review; the largest six are shown.`:`The five largest positions are shown. Sector or asset-class allocation requires verified classifications.`}</p></div></div></div>;
}
export function ConcentrationSlide({holdings}) {
 const ranked=[...holdings].sort((a,b)=>b.value-a.value),total=ranked.reduce((n,h)=>n+h.value,0),largest=ranked[0],weight=largest.value/total*100;
 return <div className="concentration-slide"><span className="slide-kicker">POSITION SENSITIVITY</span><h2>What one position can mean for the portfolio</h2><div className="sensitivity-layout"><div><span className="slide-kicker">LARGEST HOLDING</span><h3>{largest.ticker}</h3><strong>{weight.toFixed(1)}%</strong><p>{money(largest.value)} of supplied portfolio value</p></div><div className="sensitivity-scenario"><span className="slide-kicker">ILLUSTRATIVE SCENARIO</span><h3>If {largest.ticker} declined 10%</h3><strong>−{(weight*.1).toFixed(2)}%</strong><p>Portfolio impact: −{money(largest.value*.1)}</p><small>Assumes every other position stays unchanged. An illustration of position size, not a forecast or risk model.</small></div></div><div className="sensitivity-strip">{ranked.slice(0,3).map(h=><div key={h.ticker}><b>{h.ticker}</b><span>{(h.value/total*100).toFixed(1)}% of portfolio</span></div>)}</div></div>;
}
