import React from 'react';
import {groupPositions} from './supporting-data.js';
const usd=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const pct=n=>`${n>0?'+':''}${n.toFixed(2)}%`;
const signed=n=>`${Number(n)>0?'+':''}${Number(n).toFixed(1)}%`;
const colors=['#1b2a4a','#3a608c','#648ab0','#8cadce','#b5cbe0','#d5e2ee'];
export function AssetAllocationSlide({positions,source}) {
 const groups=groupPositions(positions,'assetClass'),total=positions.reduce((n,h)=>n+h.value,0);
 const chart=groups.length>6?[...groups.slice(0,5),{name:'Other',value:groups.slice(5).reduce((n,g)=>n+g.value,0)}]:groups;
 let cursor=0;const stops=chart.map((g,i)=>{const start=cursor;cursor+=g.value/total*100;return `${colors[i]} ${start}% ${cursor}%`;}).join(',');
 return <div className="asset-slide"><span className="slide-kicker">PORTFOLIO OVERVIEW</span><h2>Overall asset allocation</h2><div className="asset-layout"><div><div className="allocation-donut" style={{background:`conic-gradient(${stops})`}} role="img" aria-label="Uploaded asset-class allocation. Exact weights appear in the table."><div className="allocation-donut-center"><strong>{groups.length}</strong><span>asset classes</span></div></div><p className="asset-total">Total portfolio <b>{usd(total)}</b></p></div><div><table><thead><tr><th>ASSET CLASS</th><th>VALUE</th><th>WEIGHT</th></tr></thead><tbody>{chart.map((g,i)=><tr key={g.name}><td><i style={{background:colors[i]}}/>{g.name}</td><td>{usd(g.value)}</td><td>{(g.value/total*100).toFixed(1)}%</td></tr>)}</tbody></table><p className="context-source">Classifications come from the uploaded holdings. Other combines smaller classes when needed.</p></div></div><p className="context-source">Source: {source || 'Uploaded holdings'}.</p></div>;
}
const assetBucket = value => {
 const v=String(value||'').toLowerCase();
 if(/fixed|bond|income|treas|municipal|muni|cash|money market|cd\b|certificate/.test(v)) return 'Fixed income / cash';
 if(/equity|stock|common|preferred|reit|etf|large cap|small cap|mid cap/.test(v)) return 'Equities';
 return value?.trim() || 'Unclassified';
};
export function AccountSummarySlide({positions,source}) {
 const total=positions.reduce((n,h)=>n+h.value,0),assetRows=positions.map(p=>({...p,bucket:assetBucket(p.assetClass)}));
 const buckets=groupPositions(assetRows,'bucket'),accounts=groupPositions(positions,'account');
 const known=buckets.filter(g=>g.name!=='Unclassified'),classified=known.reduce((n,g)=>n+g.value,0);
 return <div className="account-summary-slide"><span className="slide-kicker">ACCOUNT SUMMARY</span><h2>How the portfolio is built</h2><div className="account-summary-head"><div><span className="account-summary-label">TOTAL PORTFOLIO</span><strong>{usd(total)}</strong><p>{positions.length} supplied positions · {accounts.length} account{accounts.length===1?'':'s'}</p></div><div className="account-summary-note"><span className="account-summary-label">MAJOR BREAKDOWN</span><p>{classified?`${(classified/total*100).toFixed(1)}% of supplied value is classified between equities and fixed income / cash.`:'Asset-class labels were not included in the upload.'}</p></div></div><div className="account-summary-layout"><div className="asset-balance"><h3>Equities vs. fixed income</h3>{buckets.filter(g=>g.name!=='Unclassified').slice(0,3).map(g=><div className="asset-balance-row" key={g.name}><div><span>{g.name}</span><b>{(g.value/total*100).toFixed(1)}%</b></div><div className="asset-balance-track"><i className={g.name.startsWith('Equities')?'equity-fill':'fixed-fill'} style={{width:`${g.value/total*100}%`}}/></div><small>{usd(g.value)}</small></div>)}{!known.length&&<div className="data-pending compact"><p>Upload a classified holdings file to separate equities from fixed income.</p></div>}</div><div className="account-breakdown"><h3>By account</h3><table><thead><tr><th>ACCOUNT</th><th>VALUE</th><th>WEIGHT</th></tr></thead><tbody>{accounts.slice(0,6).map(g=><tr key={g.name}><td>{g.name}</td><td>{usd(g.value)}</td><td>{(g.value/total*100).toFixed(1)}%</td></tr>)}</tbody></table>{accounts.length>6&&<p className="composition-note">Showing the six largest accounts.</p>}</div></div><p className="context-source">Source: {source || 'Uploaded holdings'}. Fixed income / cash and equity buckets use the uploaded asset-class labels; unclassified positions remain visible rather than being guessed.</p></div>;
}
export function RiskSlide({data,offset=0}) {
 return <div className="risk-slide"><div className="report-heading"><div><span className="slide-kicker">PORTFOLIO ANALYTICS</span><h2>Risk metrics review</h2></div><span>As of {data.asOf}</span></div><div className="risk-accounts">{data.accounts.slice(offset,offset+2).map((a,i)=><section key={i} className="risk-account"><div className="risk-account-heading"><h3>{a.name}</h3><span>Risk score <b>{a.score}</b></span></div><span className="slide-kicker">PORTFOLIO VALUE</span><strong className="risk-value">{usd(a.value)}</strong><p className="range-label">{a.confidence}% historical range ({a.horizonMonths} months)</p><div className="risk-range"><div><b>{pct(a.lowerPct)}</b><span>{usd(a.value*a.lowerPct/100)}</span></div><div><b>{pct(a.upperPct)}</b><span>{usd(a.value*a.upperPct/100)}</span></div></div><div className="risk-range-line"/><dl>{[['Riskalyze GPA®',a.gpa,false],['Annual dividend',a.dividend,true],['Annual range midpoint',a.midpoint,true]].filter(([,v])=>v!=null).map(([label,v,isPct])=><div key={label}><dt>{label}</dt><dd>{v.toFixed(isPct?2:1)}{isPct?'%':''}</dd></div>)}</dl></section>)}</div><p className="context-source">Source: {data.source}. {data.scope || 'Values and analytics reflect the supplied risk report.'} Dollar ranges use each report account value and its percentage range. Historical ranges are not guarantees.</p></div>;
}
export function AttributionSlide({data,accountIndex=0}) {
 const account=data.accounts[accountIndex],ranked=[...account.holdings].sort((a,b)=>b.contribution-a.contribution),positive=ranked.filter(h=>h.contribution>0).slice(0,5),negative=[...ranked].reverse().filter(h=>h.contribution<0).slice(0,5);
 const list=(rows,title)=><section><h3>{title}</h3><table><thead><tr><th>SECURITY</th><th>RETURN</th><th>CONTRIB.</th></tr></thead><tbody>{rows.map(h=><tr key={h.ticker}><td><b>{h.ticker}</b>{h.name&&<span>{h.name}</span>}</td><td>{h.return==null?'—':pct(h.return)}</td><td>{pct(h.contribution)}</td></tr>)}</tbody></table>{!rows.length&&<p className="helper">No {title.toLowerCase()} in the supplied data.</p>}</section>;
 return <div className="attribution-slide"><div className="report-heading"><div><span className="slide-kicker">{account.name}</span><h2>Performance contribution</h2></div><span>{data.periodStart} to {data.periodEnd}</span></div><div className="contribution-columns">{list(positive,'Top contributors')}{list(negative,'Top detractors')}</div><p className="contribution-takeaway">{positive.length?`${positive[0].ticker} contributed the most among supplied positions (${pct(positive[0].contribution)}). `:''}{negative.length?`${negative[0].ticker} was the largest detractor (${pct(negative[0].contribution)}).`:''}</p><p className="context-source">Source: {data.source}. {data.feeBasis}. Reported contribution to return, in percentage points. Up to five contributors and five detractors from the supplied data. Figures are not recalculated from current position weights.</p></div>;
}
export function RegionalAttributionSlide({positions,data}) {
 const total=positions.reduce((n,h)=>n+h.value,0),groups=groupPositions(positions,'region'),indexes=data?.indexes||[],hasRegion=groups.some(g=>g.name!=='Unclassified');
 const rows=indexes.map(index=>{const match=groups.find(g=>g.name.toLowerCase()===String(index.region).toLowerCase());const weight=match?match.value/total*100:0;const ret=Number(index.return);return {...index,weight,contribution:Number.isFinite(ret)?weight*ret/100:null};});
 return <div className="regional-attribution-slide"><div className="report-heading"><div><span className="slide-kicker">REGIONAL ATTRIBUTION</span><h2>Where the portfolio participated</h2></div><span>{data?.asOf?`YTD through ${data.asOf}`:'Awaiting market data'}</span></div>{!hasRegion?<div className="data-pending"><span className="slide-kicker">REGION DATA NEEDED</span><h3>Match the holdings to the same regions as the market snapshot.</h3><p>Add a Region / Geography column to the uploaded holdings file. The slide will then compare each client weight with the corresponding index return without inferring a region from a ticker.</p></div>:<><div className="regional-table"><div className="regional-table-head"><span>REGION / INDEX</span><span>CLIENT WEIGHT</span><span>YTD RETURN</span><span>WEIGHTED CONTRIBUTION*</span></div>{rows.map(row=><div className="regional-table-row" key={row.id}><div><b>{row.region}</b><small>{row.label}</small></div><strong>{row.weight?`${row.weight.toFixed(1)}%`:'—'}</strong><strong>{Number.isFinite(Number(row.return))?signed(row.return):'—'}</strong><strong>{row.contribution==null?'—':signed(row.contribution)}</strong></div>)}</div><p className="regional-note">*Illustrative exposure contribution = client regional weight × supplied YTD index return. It is not security-level performance attribution.</p></>}<p className="context-source">{data?.source||'Sourced market context'}{data?.asOf?` Through ${data.asOf}.`:'.'} Regional weights are calculated from the uploaded holdings; unmapped positions are not silently reassigned.</p></div>;
}
